name: Daily Telegram Poll

on:
  schedule:
    - cron: '*/5 * * * *'  # مؤقتًا: كل 5 دقائق للتجربة
  workflow_dispatch:

jobs:
  send-poll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install python-telegram-bot schedule flask

      - name: Run bot
        run: python main.py
